# Generated by Django 5.2.6 on 2025-09-24 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(max_length=500)),
                ('industry', models.CharField(blank=True, help_text='e.g., E-commerce, SaaS, Local Restaurant', max_length=255, null=True)),
                ('business_description', models.TextField(help_text='A brief description of the business, its mission, and what it does.')),
                ('products_or_services', models.TextField(help_text='List the main products or services offered. Separate items with a new line.')),
                ('target_audience', models.TextField(help_text='Describe the ideal customer (e.g., age, interests, location).')),
                ('target_locations', models.CharField(help_text='Comma-separated list of cities, states, or countries to target.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
