# Generated by Django 5.2.6 on 2025-09-24 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_businessprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_description', models.TextField(blank=True, null=True)),
                ('daily_budget', models.DecimalField(decimal_places=2, help_text='Daily budget in USD', max_digits=10)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget in USD', max_digits=10, null=True)),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text='Amount per click in USD', max_digits=10)),
                ('campaign_type', models.CharField(choices=[('search', 'Search Campaign'), ('display', 'Display Campaign'), ('video', 'Video Campaign'), ('shopping', 'Shopping Campaign'), ('app', 'App Campaign')], default='search', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('target_locations', models.TextField(help_text='Comma-separated list of target locations')),
                ('target_languages', models.CharField(blank=True, help_text='Comma-separated list of target languages', max_length=500, null=True)),
                ('keywords', models.JSONField(default=list, help_text='List of keywords with match types')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.useradaccount')),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'ad_account', 'campaign_name')},
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=100)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('phrase', 'Phrase Match'), ('broad', 'Broad Match'), ('broad_match_modifier', 'Broad Match Modifier')], default='broad', max_length=20)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Custom bid amount for this keyword', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_set', to='api.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'keyword_text', 'match_type')},
            },
        ),
    ]
