# Generated by Django 5.2.6 on 2025-09-25 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_campaign_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, help_text="Cost in your account's currency", max_digits=12)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='api.campaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='KeywordPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='api.keyword')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('keyword', 'date')},
            },
        ),
    ]
